04/05/2023 03:32:25 PM [INFO] Added parameter: Conv2DSize: min=1, max=256, is_integer=True, resolution=1, stages=6
04/05/2023 03:32:25 PM [INFO] Added parameter: Dense1Size: min=512, max=1024, is_integer=True, resolution=1, stages=8
04/05/2023 03:32:25 PM [INFO] Added parameter: Dropout1: min=0.1, max=0.9, is_integer=False, resolution=0.1, stages=2
04/05/2023 03:32:25 PM [INFO] Beginning run:
<ltpspace.Explorer object at 0x0000021F3B1F7C50>
04/05/2023 03:32:25 PM [INFO] Recovering from: Logfiles\ltps_2023-04-05_15-27-57.log
04/05/2023 03:32:25 PM [INFO] Recovered score: 0.7430728646318615
04/05/2023 03:32:25 PM [INFO] Recovered params: [213, 820, 0.8]
04/05/2023 03:32:25 PM [INFO] Recovered currentparam: 1
04/05/2023 03:32:25 PM [INFO] Recovered direction: True
04/05/2023 03:32:25 PM [INFO] Recovered stages: 7
04/05/2023 03:32:25 PM [INFO] Beginning Parameter Space Search...
04/05/2023 03:32:25 PM [INFO] Status Update - Score: 0.7430728646318615; Parameters: [213, 820, 0.8]; Currentparam: 1; Direction: True; Stage: 7;
04/05/2023 03:32:26 PM [DEBUG] Trying Dense1Size from 820 to 948
04/05/2023 03:32:29 PM [ERROR] Unexpected error occurred: in user code:

    File "C:\Users\cpnbe\AppData\Roaming\Python\Python311\site-packages\keras\engine\training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py", line 1153, in f1_score  *
        zero_division=zero_division,
    File "C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py", line 1285, in fbeta_score  *
        _, _, f, _ = precision_recall_fscore_support(
    File "C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py", line 1568, in precision_recall_fscore_support  *
        labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
    File "C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py", line 1374, in _check_set_wise_labels  *
        y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    File "C:\Python311\Lib\site-packages\sklearn\metrics\_classification.py", line 86, in _check_targets  *
        check_consistent_length(y_true, y_pred)
    File "C:\Python311\Lib\site-packages\sklearn\utils\validation.py", line 395, in check_consistent_length  *
        uniques = np.unique(lengths)
    File "<__array_function__ internals>", line 180, in unique  **
        
    File "C:\Users\cpnbe\AppData\Roaming\Python\Python311\site-packages\numpy\lib\arraysetops.py", line 272, in unique
        ar = np.asanyarray(ar)

    NotImplementedError: Cannot convert a symbolic tf.Tensor (strided_slice_1:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported.

